# Ensemble learning 

Ensemble learning is a technique in which we train so many model on our given dataset.

And the small model which train on the training dataset called week model

Now whatever sample we get will predict there class using the combination of week models.


Strong model: these small model collectively represent a strong model.


Ensemble(group) learning techniques:

Bagging

1> Randomforest regression

2> Randomforest classifier

3> BaggingClassifier

4> BaggingRegressor

etc

Boosting

Note: In Bootstrap same number of sample come in the training of week model and each weak model may contain duplicat sample manytime.

1> AdaBoost Classifier

2> AdaBoost Regressor

etc

Stacking

1> VotingClassifier

2> VotingRegressor

etc

# Bagging Classification:

RandomForest classifier

In [1]:
from sklearn.datasets import load_iris

In [2]:
data=load_iris()

In [5]:
X=data.data      # feature of iris dataset

In [7]:
y=data.target   # target of iris dataset

In [8]:
from sklearn.ensemble import RandomForestClassifier

In [9]:
model=RandomForestClassifier()

In [10]:
model.fit(X,y)

RandomForestClassifier()

In [12]:
model.predict([[5.1, 3.5, 1.4, 0.2]])

array([0])

In [25]:
model.predict_proba([[5.1, 3.5, 1.4, 0.2]])

array([[1., 0., 0.]])

In [14]:
import numpy as np

In [15]:
np.argmax([100,200,19])

1

In [21]:
from sklearn.ensemble import BaggingClassifier
from sklearn.linear_model import LogisticRegression

In [32]:
   #KNN, LogisticRegression,DecisionTree
base=LogisticRegression(max_iter=200)
model2=BaggingClassifier(base_estimator=base,n_estimators=10) 
model2.fit(X,y)

BaggingClassifier(base_estimator=LogisticRegression(max_iter=200))

In [33]:
model2.predict([[5.1, 3.5, 1.4, 0.2]])

array([0])

In [34]:
model2.predict_proba([[5.1, 3.5, 1.4, 0.2]])

array([[9.81261464e-01, 1.87385216e-02, 1.45830490e-08]])

# Boosting 

In [53]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.preprocessing import MinMaxScaler
sc=MinMaxScaler()
X_sc=sc.fit_transform(X)

In [55]:
model3=AdaBoostClassifier(base_estimator=base,n_estimators=50)
model3.fit(X_sc,y)

AdaBoostClassifier(base_estimator=LogisticRegression(max_iter=200))

In [57]:
sample=[[5.1, 3.5, 1.4, 0.2]]
sample_sc=sc.transform(sample)
print(sample_sc)
model3.predict(sample_sc)

[[0.22222222 0.625      0.06779661 0.04166667]]


array([0])

In [60]:
model3.predict_proba(sample_sc)

array([[0.35500195, 0.34030323, 0.30469481]])

In [5]:
from sklearn.datasets import load_breast_cancer

In [6]:
data=load_breast_cancer()

In [8]:
print(data['DESCR'])

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

In [14]:
X=data.data   # feature

In [15]:
y=data.target  # target

In [18]:
from sklearn.ensemble import VotingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [31]:
weekModel1=KNeighborsClassifier()
weekModel2=LogisticRegression(max_iter=3000)
weekModel3=DecisionTreeClassifier()
model4=VotingClassifier(estimators=[('model1',weekModel1),('model2',weekModel2),('model3',weekModel3)])

In [32]:
model4.fit(X,y)

VotingClassifier(estimators=[('model1', KNeighborsClassifier()),
                             ('model2', LogisticRegression(max_iter=3000)),
                             ('model3', DecisionTreeClassifier())])

In [35]:
model4.predict([[1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
       3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
       8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
       3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
       1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01]])

array([0])

In [36]:
sample=[[1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
       3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
       8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
       3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
       1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01]]

In [38]:
from sklearn.preprocessing import Binarizer

In [40]:
sc=Binarizer()

In [41]:
X_sc=sc.fit_transform(X)

In [42]:
X_sc

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 0., 1., 1.]])

In [62]:
weekModel1=KNeighborsClassifier()
weekModel2=LogisticRegression(max_iter=30)
weekModel3=DecisionTreeClassifier()
model5=VotingClassifier(estimators=[('model1',weekModel1),('model2',weekModel2),('model3',weekModel3)],voting='soft')

In [63]:
model5.fit(X_sc,y)

VotingClassifier(estimators=[('model1', KNeighborsClassifier()),
                             ('model2', LogisticRegression(max_iter=30)),
                             ('model3', DecisionTreeClassifier())],
                 voting='soft')

In [64]:
Sample_sc=sc.transform(sample)

In [65]:
model5.predict(Sample_sc)

array([0])

In [66]:
model5.predict_proba(Sample_sc)

array([[0.58725002, 0.41274998]])

In [73]:
str1='xyz'   #xyc
str2='abc'   #abz
def swapping(str1,str2):
    new_str1=str1[:2]+str2[-1]
    print(new_str1)
    new_str2=str2[:2]+str1[-1]
    print(new_str2)

In [74]:
a='klm'  #klp
b='nop'  #nom
swapping(a,b)

klp
nom
