In [23]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("fraud_detection_bank_dataset.csv")

In [3]:
df

Unnamed: 0  col_0  col_1  col_2  col_3  col_4  col_5  col_6  col_7  \
0               0      9   1354      0     18      0      1      7      9   
1               1      0    239      0      1      0      1      0      0   
2               2      0    260      0      4      0      3      6      0   
3               3     17    682      0      1      0      0      8     17   
4               4      1    540      0      2      0      1      7      1   
...           ...    ...    ...    ...    ...    ...    ...    ...    ...   
20463       20463      0     88      0      0      0      2     -1      0   
20464       20464      0    134      0      2      0      0      6      0   
20465       20465      4    393      1      1      0      0     -1      4   
20466       20466      0     10      0      1      0      0     -1      0   
20467       20467      4    399      0      3      0      1      7      4   

       col_8  ...  col_103  col_104  col_105  col_106  col_107  col_108  \
0          0  ...        0        0        0        1        1        0   
1          0  ...        0        1        0        0        0        0   
2          0  ...        0        0        0        1        1        0   
3          0  ...        0        1        0        1        1        0   
4          0  ...        0        0        0        1        1        0   
...      ...  ...      ...      ...      ...      ...      ...      ...   
20463      0  ...        0        1        0        0        0        0   
20464      0  ...        0        0        0        0        0        0   
20465      0  ...        0        1        0        0        0        0   
20466      0  ...        0        0        0        0        0        0   
20467      0  ...        0        1        0        1        1        0   

       col_109  col_110  col_111  targets  
0            0        0       49        1  
1            0        0       55        1  
2            0        0       56        1  
3            0        0       65        1  
4            0        0      175        1  
...        ...      ...      ...      ...  
20463        1        0       85        0  
20464        0        0        7        0  
20465        0        0       45        0  
20466        0        0        5        0  
20467        0        0       72        0  

[20468 rows x 114 columns]

In [9]:
df.targets[df['targets']==1].count()

5438

In [10]:
df.targets[df['targets']==0].count()

15030

In [15]:
X=df.iloc[:,1:-1].values
X

array([[9.000e+00, 1.354e+03, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        4.900e+01],
       [0.000e+00, 2.390e+02, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        5.500e+01],
       [0.000e+00, 2.600e+02, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        5.600e+01],
       ...,
       [4.000e+00, 3.930e+02, 1.000e+00, ..., 0.000e+00, 0.000e+00,
        4.500e+01],
       [0.000e+00, 1.000e+01, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        5.000e+00],
       [4.000e+00, 3.990e+02, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        7.200e+01]])

In [17]:
y=df.iloc[:,-1].values
y

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [11]:
from imblearn.over_sampling import SMOTE

In [12]:
sm=SMOTE()

In [34]:
X_sm,y_sm=sm.fit_resample(X,y)


In [35]:
len(X_sm)

30060

In [36]:
y_sm

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [37]:
counter_0=0
counter_1=0
for i in y_sm:
    if i==0:
        counter_0+=1
    else:
        counter_1+=1
print("counter_0 :",counter_0)
print("counter_1 :",counter_1)

counter_0 : 15030
counter_1 : 15030


In [38]:
a=np.array([[1,2,3,4],[2,3,4,5]])

In [39]:
a

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [40]:
np.max(a)

5

In [41]:
a/5

array([[0.2, 0.4, 0.6, 0.8],
       [0.4, 0.6, 0.8, 1. ]])

# Scaling

In [42]:
from sklearn.preprocessing import MinMaxScaler

In [43]:
scale=MinMaxScaler()

In [45]:
X_scale=scale.fit_transform(X_sm)

In [46]:
from sklearn.linear_model import LogisticRegression      # classification model

In [57]:
model=LogisticRegression(max_iter=200)

In [58]:
model.fit(X_scale,y_sm)

LogisticRegression(max_iter=200)

In [60]:
sample=X_scale[0]
y_sm[0]

1

In [61]:
model.predict([sample])

array([0], dtype=int64)

In [62]:
from sklearn.metrics import accuracy_score

In [64]:
model.score(X_scale,y_sm)       # 1 st Rule to get accuracy

0.8389221556886227

In [65]:
y_pred=model.predict(X_scale)

In [68]:
accuracy_score(y_pred,y_sm)     # 2nd Rule to get accuracy after importing accuracy score is mendatory

0.8389221556886227

In [70]:
sample=X_scale[2]
y_sm[2]

1

In [71]:
model.predict([sample])

array([0], dtype=int64)

In [74]:
y_sm[:10]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [73]:
y_pred[:10]

array([0, 1, 0, 0, 0, 1, 0, 0, 1, 1], dtype=int64)

In [76]:
model.predict([X_scale[1]])

array([1], dtype=int64)

In [77]:
df

Unnamed: 0  col_0  col_1  col_2  col_3  col_4  col_5  col_6  col_7  \
0               0      9   1354      0     18      0      1      7      9   
1               1      0    239      0      1      0      1      0      0   
2               2      0    260      0      4      0      3      6      0   
3               3     17    682      0      1      0      0      8     17   
4               4      1    540      0      2      0      1      7      1   
...           ...    ...    ...    ...    ...    ...    ...    ...    ...   
20463       20463      0     88      0      0      0      2     -1      0   
20464       20464      0    134      0      2      0      0      6      0   
20465       20465      4    393      1      1      0      0     -1      4   
20466       20466      0     10      0      1      0      0     -1      0   
20467       20467      4    399      0      3      0      1      7      4   

       col_8  ...  col_103  col_104  col_105  col_106  col_107  col_108  \
0          0  ...        0        0        0        1        1        0   
1          0  ...        0        1        0        0        0        0   
2          0  ...        0        0        0        1        1        0   
3          0  ...        0        1        0        1        1        0   
4          0  ...        0        0        0        1        1        0   
...      ...  ...      ...      ...      ...      ...      ...      ...   
20463      0  ...        0        1        0        0        0        0   
20464      0  ...        0        0        0        0        0        0   
20465      0  ...        0        1        0        0        0        0   
20466      0  ...        0        0        0        0        0        0   
20467      0  ...        0        1        0        1        1        0   

       col_109  col_110  col_111  targets  
0            0        0       49        1  
1            0        0       55        1  
2            0        0       56        1  
3            0        0       65        1  
4            0        0      175        1  
...        ...      ...      ...      ...  
20463        1        0       85        0  
20464        0        0        7        0  
20465        0        0       45        0  
20466        0        0        5        0  
20467        0        0       72        0  

[20468 rows x 114 columns]

# Train_test_split(): 

it help us to break our dataframe into two part Training data and testing Data

In [89]:
df

Unnamed: 0  col_0  col_1  col_2  col_3  col_4  col_5  col_6  col_7  \
0               0      9   1354      0     18      0      1      7      9   
1               1      0    239      0      1      0      1      0      0   
2               2      0    260      0      4      0      3      6      0   
3               3     17    682      0      1      0      0      8     17   
4               4      1    540      0      2      0      1      7      1   
...           ...    ...    ...    ...    ...    ...    ...    ...    ...   
20463       20463      0     88      0      0      0      2     -1      0   
20464       20464      0    134      0      2      0      0      6      0   
20465       20465      4    393      1      1      0      0     -1      4   
20466       20466      0     10      0      1      0      0     -1      0   
20467       20467      4    399      0      3      0      1      7      4   

       col_8  ...  col_103  col_104  col_105  col_106  col_107  col_108  \
0          0  ...        0        0        0        1        1        0   
1          0  ...        0        1        0        0        0        0   
2          0  ...        0        0        0        1        1        0   
3          0  ...        0        1        0        1        1        0   
4          0  ...        0        0        0        1        1        0   
...      ...  ...      ...      ...      ...      ...      ...      ...   
20463      0  ...        0        1        0        0        0        0   
20464      0  ...        0        0        0        0        0        0   
20465      0  ...        0        1        0        0        0        0   
20466      0  ...        0        0        0        0        0        0   
20467      0  ...        0        1        0        1        1        0   

       col_109  col_110  col_111  targets  
0            0        0       49        1  
1            0        0       55        1  
2            0        0       56        1  
3            0        0       65        1  
4            0        0      175        1  
...        ...      ...      ...      ...  
20463        1        0       85        0  
20464        0        0        7        0  
20465        0        0       45        0  
20466        0        0        5        0  
20467        0        0       72        0  

[20468 rows x 114 columns]

In [90]:
X=df.iloc[:,1:-1].values

In [91]:
X

array([[9.000e+00, 1.354e+03, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        4.900e+01],
       [0.000e+00, 2.390e+02, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        5.500e+01],
       [0.000e+00, 2.600e+02, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        5.600e+01],
       ...,
       [4.000e+00, 3.930e+02, 1.000e+00, ..., 0.000e+00, 0.000e+00,
        4.500e+01],
       [0.000e+00, 1.000e+01, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        5.000e+00],
       [4.000e+00, 3.990e+02, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        7.200e+01]])

In [92]:
y=df.iloc[:,-1].values
y

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [93]:
sm=SMOTE()
X_sm,y_sm=sm.fit_resample(X,y)

In [94]:
X_sm.shape

(30060, 112)

In [95]:
scale=MinMaxScaler()
X_scale=scale.fit_transform(X_sm)

In [96]:
X_scale

array([[0.00391134, 0.03581253, 0.        , ..., 0.        , 0.        ,
        0.06559572],
       [0.        , 0.00632141, 0.        , ..., 0.        , 0.        ,
        0.07362784],
       [0.        , 0.00687685, 0.        , ..., 0.        , 0.        ,
        0.07496653],
       ...,
       [0.        , 0.00056384, 0.        , ..., 0.        , 0.        ,
        0.10040161],
       [0.00049587, 0.00603039, 0.        , ..., 0.        , 0.        ,
        0.02587382],
       [0.00159554, 0.01100659, 0.        , ..., 0.        , 0.        ,
        0.05719209]])

In [97]:
from sklearn.model_selection import train_test_split

In [99]:
X_train,X_test,y_train,y_test=train_test_split(X_scale,y_sm,random_state=42,train_size=0.7)

In [100]:
model2=LogisticRegression(max_iter=200)

In [101]:
model2.fit(X_train,y_train)

LogisticRegression(max_iter=200)

In [102]:
y_Train_pred=model2.predict(X_train)

In [103]:
accuracy_score(y_Train_pred,y_train)

0.8298165573614675

In [104]:
y_test_pred=model2.predict(X_test)

In [105]:
accuracy_score(y_test_pred,y_test)

0.8286759813705922

# Polynomial feature

When we have less number of feature to understand the target then we increase number of 
features using polynomial features.

In [1]:
import pandas as pd

In [15]:
df1=pd.DataFrame({'length(cm)':[2,4,5,6,8,9,7],
             'Target':['Apple','Apple','Apple','Banana','Banana','Banana','Apple']})

In [16]:
df1

length(cm)  Target
0           2   Apple
1           4   Apple
2           5   Apple
3           6  Banana
4           8  Banana
5           9  Banana
6           7   Apple

In [17]:
X=df1.iloc[:,:-1].values
X                              # features

array([[2],
       [4],
       [5],
       [6],
       [8],
       [9],
       [7]], dtype=int64)

In [18]:
y=df1.iloc[:,-1].values
y                            # Target

array(['Apple', 'Apple', 'Apple', 'Banana', 'Banana', 'Banana', 'Apple'],
      dtype=object)

In [19]:
from sklearn.linear_model import LogisticRegression

In [20]:
model1=LogisticRegression()

In [21]:
model1.fit(X,y)

LogisticRegression()

In [22]:
model1.predict([[4]])

array(['Apple'], dtype=object)

In [23]:
model1.predict([[7]])

array(['Banana'], dtype=object)

In [24]:
model1.predict([[5.5]])

array(['Apple'], dtype=object)

In [55]:
model1.predict([[6]])

array(['Apple'], dtype=object)

In [26]:
from sklearn.preprocessing import PolynomialFeatures

In [31]:
pl=PolynomialFeatures(degree=3)

In [32]:
X_pl=pl.fit_transform(X)

In [35]:
df2=pd.DataFrame(X_pl)

In [36]:
df2

0    1     2      3
0  1.0  2.0   4.0    8.0
1  1.0  4.0  16.0   64.0
2  1.0  5.0  25.0  125.0
3  1.0  6.0  36.0  216.0
4  1.0  8.0  64.0  512.0
5  1.0  9.0  81.0  729.0
6  1.0  7.0  49.0  343.0

In [51]:
X_feature_pl=df2.iloc[:,1:]
X_feature_pl


1     2      3
0  2.0   4.0    8.0
1  4.0  16.0   64.0
2  5.0  25.0  125.0
3  6.0  36.0  216.0
4  8.0  64.0  512.0
5  9.0  81.0  729.0
6  7.0  49.0  343.0

In [52]:
X_feature_pl=X_feature_pl.values

In [40]:

model3=LogisticRegression()

In [41]:
model3.fit(X_feature_pl,y)

LogisticRegression()

In [47]:
sample=pl.transform([[6]])
sample1=sample[0][1:]
print(sample1)
model3.predict([sample1])

[  6.  36. 216.]


array(['Apple'], dtype=object)

In [53]:
sample=pl.transform([[7]])
sample1=sample[0][1:]
print(sample1)
model3.predict([sample1])

[  7.  49. 343.]


array(['Banana'], dtype=object)

# Decision Tree and Logistic regression with over and multinominal concept